// Generated by Selenium IDE
import { Builder, By, Key, until } from 'selenium-webdriver'
import assert from 'assert'

describe('open_dou', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  // afterEach(async function() {
  //   await driver.quit();
  // })
  it('open_dou', async function() {
    await driver.get("https://dou.ua/")
    await driver.manage().window().setRect(550, 691)
    await driver.findElement(By.css(".b-head li:nth-child(5) > a")).click()
    await driver.findElement(By.linkText("Java вакансии в Киеве")).click()
    await driver.close()
  })
})
















































